#!/usr/bin/env bash
# Regenerate docs/CORPUS_MANIFEST.md — SHA-256 fingerprints of the
# git-ignored measurement inputs (run 12, second-desk verification).
#
# The corpora cannot be committed (book-trial transcriptions are private
# by licensing posture; quiet_fens derives from TWIC ground that must
# not be redistributed), so a verifier can match a binary to a ref but
# not the inputs to the figures. Hashes are not content: this manifest
# closes that gap. Regenerate and commit it in the SAME commit as any
# corpus change.
set -euo pipefail
cd "$(dirname "$0")/.."
out=docs/CORPUS_MANIFEST.md
{
  echo "# Corpus manifest"
  echo
  echo "SHA-256 fingerprints of the git-ignored measurement inputs, so a"
  echo "second desk can verify that a re-run used the same corpora the"
  echo "published figures were computed on. Regenerated by"
  echo '`scripts/corpus_manifest.sh`; stale hashes mean the figures and'
  echo "the corpus have diverged and the most recent measurement wins."
  echo
  echo '```'
  for f in testdata/private/book-trials/*.json testdata/corpus/quiet_fens.txt; do
    n=""
    case "$f" in
      *.json) n="$(python3 -c "import json;print(len(json.load(open('$f'))['positions']),'positions')" 2>/dev/null || echo '?')" ;;
      *quiet_fens*) n="$(grep -c . "$f") lines" ;;
    esac
    printf '%s  %-52s %s\n' "$(shasum -a 256 "$f" | cut -d' ' -f1)" "$f" "($n)"
  done
  echo '```'
} > "$out"
echo "wrote $out"
